databaseChangeLog:
    -   changeSet:
            id: create-product-to-category-table
            author: nkgrz
            changes:
                -   createTable:
                        tableName: product_to_category
                        columns:
                            -   column:
                                    name: product_id
                                    type: uuid
                                    constraints:
                                        nullable: false
                            -   column:
                                    name: category_id
                                    type: uuid
                                    constraints:
                                        nullable: false

                -   addPrimaryKey:
                        tableName: product_to_category
                        columnNames: product_id, category_id
                        constraintName: pk_product_to_category

                -   addForeignKeyConstraint:
                        baseTableName: product_to_category
                        baseColumnNames: product_id
                        referencedTableName: product
                        referencedColumnNames: id
                        constraintName: fk_product_to_category_product

                -   addForeignKeyConstraint:
                        baseTableName: product_to_category
                        baseColumnNames: category_id
                        referencedTableName: category
                        referencedColumnNames: id
                        constraintName: fk_product_to_category_category